export const sampleWines = [
  {
    id: 'wv-001',
    name: 'Château Royal Cabernet Sauvignon',
    description: 'A full-bodied, majestic Cabernet bursting with layers of dark cherry, cedar, and velvety tannins.',
    image: '/wines/cabernet.png',
    category: 'Red Wine',
    country_origin: 'France',
    bottle_size: '750ml',
    vintage_year: 2015,
    stock: 12,
    price: 349.00,
    badge: 'GRAND CRU',
    rating: 4.9,
    featured: true
  },
  {
    id: 'wv-002',
    name: 'Golden Sparkle Prestige Brut',
    description: 'An elegant, uplifting sparkling wine driven by precise minerality and a fine, persistent mousse.',
    image: '/wines/champagne.png',
    category: 'Sparkling Wine',
    country_origin: 'Italy',
    bottle_size: '750ml',
    vintage_year: 2020,
    stock: 24,
    price: 189.00,
    badge: 'BEST SELLER',
    rating: 4.7,
    featured: true
  },
  {
    id: 'wv-003',
    name: 'Opulence Chardonnay Reserve',
    description: 'A deeply expressive white wine featuring notes of toasted almond, vanilla, and bright orchard fruit.',
    image: '/wines/chardonnay.png',
    category: 'White Wine',
    country_origin: 'USA',
    bottle_size: '750ml',
    vintage_year: 2019,
    stock: 8,
    price: 125.00,
    badge: 'SOMMELIER PICK',
    rating: 4.8,
    featured: true
  },
  {
    id: 'wv-004',
    name: 'Velvet Noir Pinot Noir',
    description: 'An exceptionally smooth Pinot Noir characterized by delicate crushed raspberry and subtle earthy undertones.',
    image: '/wines/cabernet.png',
    category: 'Red Wine',
    country_origin: 'New Zealand',
    bottle_size: '750ml',
    vintage_year: 2021,
    stock: 15,
    price: 95.00,
    badge: '',
    rating: 4.6,
    featured: false
  },
  {
    id: 'wv-005',
    name: 'Blush & Breeze Rosé',
    description: 'A crisp, ethereal rosé with vivid strawberry aromatics and a refreshing, dry finish.',
    image: '/wines/rose.png',
    category: 'Rosé Wine',
    country_origin: 'France',
    bottle_size: '750ml',
    vintage_year: 2022,
    stock: 45,
    price: 65.00,
    badge: 'NEW',
    rating: 4.5,
    featured: false
  },
  {
    id: 'wv-006',
    name: 'Midnight Shiraz Eclipse',
    description: 'A bold, ink-dark Shiraz delivering intense blackberry fruit, cracked black pepper, and dark chocolate notes.',
    image: '/wines/cabernet.png',
    category: 'Red Wine',
    country_origin: 'Australia',
    bottle_size: '750ml',
    vintage_year: 2018,
    stock: 4,
    price: 215.00,
    badge: 'LIMITED',
    rating: 4.9,
    featured: true
  },
  {
    id: 'wv-007',
    name: 'Sapphire Riesling',
    description: 'A vibrant, off-dry Riesling bursting with fresh lime zest, white peach, and a piercing slate minerality.',
    image: '/wines/chardonnay.png',
    category: 'White Wine',
    country_origin: 'Germany',
    bottle_size: '750ml',
    vintage_year: 2020,
    stock: 18,
    price: 85.00,
    badge: '',
    rating: 4.6,
    featured: false
  },
  {
    id: 'wv-008',
    name: 'Imperial Cuvee Champagne',
    description: 'A highly prestigious luxury champagne showcasing toasted brioche, almond pastry, and crystalline citrus.',
    image: '/wines/champagne.png',
    category: 'Sparkling Wine',
    country_origin: 'France',
    bottle_size: '750ml',
    vintage_year: 2012,
    stock: 2,
    price: 599.00,
    badge: 'RARE',
    rating: 5.0,
    featured: true
  }
]
